server:
  shutdown: graceful

spring:
  main:
    web-application-type: none
  application:
    name: commerce-batch
  profiles:
    active: local

  config:
    import:
      - jpa.yml
      - redis.yml
      - kafka.yml
      - logging.yml
      - monitoring.yml
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd
